version: 0.2
env:
  variables:
    PIPELINE_REGION: "us-east-1"
    CLUSTER_REGION: "us-west-2"
    TARGET_AWS_ACCOUNT_ID: "836816519470"
phases:
  install:
    commands:
      - echo Starting Install Phase
      - pip install yq jq
      #Retrive CI/Build artifact which contains helm chart location and version to deploy 
      - cat $CODEBUILD_SRC_DIR_containerBuildArtifact/imagedefinitions.json
      - HELM_CHART_NAME=$(jq -r .helm_chart_name $CODEBUILD_SRC_DIR_containerBuildArtifact/imagedefinitions.json)
      - HELM_CHART_REPO=$(jq -r .helm_chart_repo $CODEBUILD_SRC_DIR_containerBuildArtifact/imagedefinitions.json)
      - HELM_CHART_VERSION=$(jq -r .helmChartVersion $CODEBUILD_SRC_DIR_containerBuildArtifact/imagedefinitions.json)
      ## Install Helm CLI 
      - echo Installing Helm
      - curl https://cgrepo.capgroup.com/repository/cgfiles/helm/helm-v3.7.2-linux-amd64.tar.gz --create-dirs --output ${TOOLS_DIR}/helm/helm.tar.gz
      - tar -xzf ${TOOLS_DIR}/helm/helm.tar.gz --strip 1 -C /usr/local/bin/ && ls -al /usr/local/bin
      - chmod +x /usr/local/bin/helm && helm version
      ## Configure helm environment variable to pull down helm charts
      - export HELM_EXPERIMENTAL_OCI=1
      ## Log into ECR repository hosting helm charts
      - aws ecr get-login-password --region $PIPELINE_REGION | helm registry login --username AWS --password-stdin 301769650010.dkr.ecr.us-east-1.amazonaws.com
  pre_build:
    commands:
  build:
    commands:
      #Retrieve cluster name from helm chart environment yaml
      - CLUSTER_NAME=$(yq -r .cluster_name helm-charts/qa.yml)
      - echo $CLUSTER_NAME
      #Assume role into Banzai Deploy Role. This role needs to be granted access to EKS Cluster. 
      - temp_role=$(aws sts assume-role --role-arn arn:aws:iam::836816519470:role/bp-inf-BB00000085-role-deploy --role-session-name eks-session)
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - export AWS_REGION=$CLUSTER_REGION
      # Authenticate to EKS Cluster 
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $CLUSTER_REGION

      ## Pull down helm charts
      - NAMESPACE=$(yq -r .namespace helm-charts/qa.yml)
      - helm pull oci://$HELM_CHART_REPO --version $HELM_CHART_VERSION
      - ls -lrt
      
      #Deploy helm chart to qa cluster 
      - echo "helm upgrade --install --atomic $HELM_CHART_NAME ./$HELM_CHART_NAME-$HELM_CHART_VERSION.tgz -f helm-charts/qa.yml --create-namespace -n $NAMESPACE"
      - helm upgrade --install --atomic $HELM_CHART_NAME ./$HELM_CHART_NAME-$HELM_CHART_VERSION.tgz -f helm-charts/qa.yml --create-namespace -n $NAMESPACE

  post_build:
    commands:
      - echo Deploy completed on `date`+
