apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port.service }}
      targetPort: {{ .Values.port.container }}
  selector:
    app: {{ .Values.name }}
